In [1]:
# Init
import os
import sys

module_path = os.path.abspath(os.path.join("../src/simulicronalpha/"))
if module_path not in sys.path:
    sys.path.append(module_path)

# Imports
import random
import numpy as np
import pandas as pd
import warnings
import multiprocessing
np.set_printoptions(suppress=True)
from numpy import concatenate as c

In [2]:
from popSim import (
    generatePopulation,
    calculateFitness,
    generateGenome,
    transposition,
    runSim,
    runBatch,
    recombination,
)

ImportError: cannot import name 'generateTransposon' from 'generateSim' (/home/siddharth/Documents/Projects/Simulicron/src/simulicronalpha/generateSim.py)

In [2]:
from generateSim import (generatePopulation, generateGenome)

In [5]:
gen,piset,piIndice = generateGenome(
    numberOfInsertionSites=1000,
    numberOfChromosomes=1,
    baseRecombinationRate=0.0,
    baseSelection=-0.1,
)
pop, tr , TEset= generatePopulation(
    gen,
    piIndice,
    NumberOfIndividual=1000,
    NumberOfTransposonTypes=2,
    NumberOfInsertionsPerType=[2,2],
    FrequencyOfInsertions=[0.5,0.5]
)

In [6]:
with np.printoptions(threshold=np.inf):
    print(pop)


[[0 0 1]
 [list([111]) list([554, 638]) 0.7408182206817179]
 [0 list([1544]) 0.9048374180359595]
 [0 0 1]
 [list([1481, 1817]) list([5, 47, 436]) 0.6065306597126334]
 [0 list([686, 889]) 0.8187307530779818]
 [0 list([1314, 1582, 1585, 1762]) 0.6703200460356393]
 [0 0 1]
 [0 0 1]
 [list([1644]) list([1005]) 0.8187307530779818]
 [list([885, 1483, 1896]) list([521]) 0.6703200460356393]
 [list([1027, 1903]) list([1673, 1791, 1899]) 0.6065306597126334]
 [0 0 1]
 [0 0 1]
 [list([1523]) list([651]) 0.8187307530779818]
 [0 list([451]) 0.9048374180359595]
 [list([887, 1256]) list([1455]) 0.7408182206817179]
 [list([214]) list([165, 226, 1099, 1190, 1230, 1761]) 0.4965853037914095]
 [list([1948]) 0 0.9048374180359595]
 [0 0 1]
 [list([16]) list([380]) 0.8187307530779818]
 [list([1668]) list([1056]) 0.8187307530779818]
 [list([1542, 1860]) list([92, 399, 587, 1993]) 0.5488116360940264]
 [0 list([1869]) 0.9048374180359595]
 [list([1154, 1870]) list([1666, 1927]) 0.6703200460356393]
 [0 0 1]
 [list

In [ ]:
gen