In [1]:
# Init
import os
import sys

module_path = os.path.abspath(os.path.join("../src/simulicronalpha/"))
if module_path not in sys.path:
    sys.path.append(module_path)

# Imports
import random
import numpy as np
import pandas as pd
import warnings
import multiprocessing
np.set_printoptions(suppress=True)
from numpy import concatenate as c

In [2]:
from popSim import (
    generateTransposon,
    generatePopulation,
    calculateFitness,
    generateGenome,
    transposition,
    runSim,
    runBatch,
    recombination,
)

In [13]:
gen,piset,piIndice = generateGenome(
    numberOfInsertionSites=1000,
    numberOfChromosomes=1,
    baseRecombinationRate=0.0,
    baseSelection=-0.1,
)
pop, tr , TEset= generatePopulation(
    gen,
    piIndice,
    NumberOfIndividual=1000,
    NumberOfTransposonTypes=2,
    NumberOfInsertionsPerType=[2,2],
    FrequencyOfInsertions=[0.5,0.5]
)

In [12]:
with np.printoptions(threshold=np.inf):
    print(pop)


[[0 0 1 0]
 [list([757, 758]) 0 0.8187307530779818 0]
 [list([1202]) list([1201]) 0.8187307530779818 0]
 [0 0 1 0]
 [list([1219, 1220]) 0 0.8187307530779818 0]
 [list([1088]) list([1087]) 0.8187307530779818 0]
 [0 list([426]) 0.9048374180359595 0]
 [list([196]) 0 0.9048374180359595 0]
 [list([171, 1313]) list([1314]) 0.7408182206817179 0]
 [0 0 1 0]
 [0 list([1141, 1142]) 0.8187307530779818 0]
 [list([1499, 1500]) 0 0.8187307530779818 0]
 [0 0 1 0]
 [list([192, 709, 710]) 0 0.7408182206817179 0]
 [0 0 1 0]
 [0 list([459]) 0.9048374180359595 0]
 [list([1038]) list([1037]) 0.8187307530779818 0]
 [0 list([272]) 0.9048374180359595 0]
 [0 list([1405, 1406]) 0.8187307530779818 0]
 [list([1077]) list([333, 1078]) 0.7408182206817179 0]
 [0 0 1 0]
 [list([43]) 0 0.9048374180359595 0]
 [list([1294]) list([1293]) 0.8187307530779818 0]
 [list([999, 1000]) 0 0.8187307530779818 0]
 [list([615, 616]) 0 0.8187307530779818 0]
 [0 0 1 0]
 [list([32]) 0 0.9048374180359595 0]
 [list([167]) list([531, 532]

In [4]:
gen

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       ...,
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])