In [1]:
# Init
import os
import sys

module_path = os.path.abspath(os.path.join("../src/simulicronalpha/"))
if module_path not in sys.path:
    sys.path.append(module_path)

# Imports
import random
import numpy as np
import pandas as pd
import warnings
import multiprocessing
np.set_printoptions(suppress=True)
from numpy import concatenate as c

In [2]:
from generateSim import (generatePopulation, generateGenome)
from stats import stats

In [3]:
gen,piset,piIndice = generateGenome(
    numberOfInsertionSites=10000,
    numberOfChromosomes=1,
    baseRecombinationRate=0.0,
    baseSelection=-0.1,
)
pop, tr , TEset= generatePopulation(
    gen,
    piIndice,
    NumberOfIndividual=1000,
    NumberOfTransposonTypes=2,
    NumberOfInsertionsPerType=[2,2],
    FrequencyOfInsertions=[0.2,0.5]
)

In [4]:
insertionSiteFrequencyArray = np.zeros((len(gen), 2,))

In [5]:
%%timeit
for i in range (1000):
    l = stats(pop, tr, TEset, insertionSiteFrequencyArray)

2.25 s ± 26.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [18]:
pop

array([[0, 0, 1],
       [list([1371]), list([527]), 0.8187307530779818],
       [list([549, 1022]), list([644, 816, 897]), 0.6065306597126334],
       ...,
       [list([914]), list([1167]), 0.8187307530779818],
       [list([1208]), 0, 0.9048374180359595],
       [list([1358]), list([842, 951, 1096]), 0.6703200460356393]],
      dtype=object)

In [19]:
tr[:,1]

array([  0., 335.,  85., ..., 271., 164., 157.])

In [20]:
l

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
unique, counts = np.unique(tr[:,1], return_counts=True)

In [22]:
# dict(zip(unique, counts))

In [23]:
sum(l[:,0])

400.0