In [ ]:
# Imports
import numpy as np
import pandas as pd
import random
import statsmodels.api as sm
from scipy.stats import linregress
from scipy.stats import chisquare
from scipy import stats
from numba import njit

# import altair as alt
import seaborn as sns
import matplotlib.pyplot as plt
from itertools import chain, repeat
import pickle
import re
from math import exp, log

# Set Seaborn style
sns.set(style="whitegrid")
plt.style.use("ggplot")
sns.set_context("talk")
%matplotlib inline

In [ ]:
[round(x) for x in np.linspace(0, 10000, 7).tolist()]

In [ ]:
int(10000 / 6)

In [ ]:
random.randrange(0, 9)

In [ ]:
chromosomeLocation = [0, 474, 687, 524]
for prime5, prime3 in zip(chromosomeLocation, chromosomeLocation[1:]):
    print(prime5, prime3)

In [ ]:
nums = np.random.choice([0, 1], size=1000, p=[0.1, 0.9]).tolist()

In [ ]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]
l[3:9]

In [ ]:
np.nonzero([1, 0, 2])[0].tolist()

In [ ]:
k = np.zeros((1000, 5,))

In [ ]:
np.all(k[:, 0:2] == 0)

In [ ]:
len(k[:, 0:2])

In [ ]:
# Set up the figure
f, (ax1, ax2, ax3) = plt.subplots(1, 3, sharey=True, figsize=(25, 10),)
# Load file from the pickle
fileName = "/home/siddharth/Documents/Projects/Simulicron/notebooks/K2U100.pickle"
with open(fileName, "rb") as f:
    result = pickle.load(f)
# Plot the average copy number
for i in result:
    f = sns.lineplot(
        x=np.arange(len(i["AvgCopyNum"])),
        y=np.asarray(i["AvgCopyNum"]),
        color="grey",
        ax=ax1,
    ).set_title("u:1.0")
# Load file from the pickle
fileName = "/home/siddharth/Documents/Projects/Simulicron/notebooks/K2U010.pickle"
with open(fileName, "rb") as f:
    result = pickle.load(f)
# Plot the average copy number
for i in result:
    sns.lineplot(
        x=np.arange(len(i["AvgCopyNum"])),
        y=np.asarray(i["AvgCopyNum"]),
        color="grey",
        ax=ax2,
    ).set_title("u:0.10")
# Load file from the pickle
fileName = "/home/siddharth/Documents/Projects/Simulicron/notebooks/K2U001.pickle"
with open(fileName, "rb") as f:
    result = pickle.load(f)
# Plot the average copy number
for i in result:
    sns.lineplot(
        x=np.arange(len(i["AvgCopyNum"])),
        y=np.asarray(i["AvgCopyNum"]),
        color="grey",
        ax=ax3,
    ).set_title("u:0.01")


fig = ax1.figure
fig.text(0.5, 0.04, "Generation", ha="center", va="center", size=18)
fig.text(
    0.05,
    0.5,
    "Avg. copy number",
    ha="center",
    va="center",
    rotation=90,
    size=18,
)

In [ ]:
numberOfInsertionSites = 10000
numberOfChromosomes = 6
chromosomeLocation = [
        round(x)
        for x in np.linspace(
            0, numberOfInsertionSites, numberOfChromosomes + 1
        ).tolist()
    ]
RecombinationRates = np.asarray([0.1] * numberOfInsertionSites)
RecombinationRates[chromosomeLocation[1:-1]] = 0.499

In [ ]:
#map=c(0,cumsum(-0.5*log(1-2*rates)))
map = np.cumsum(-0.5*np.log(1-(2*RecombinationRates)))

In [ ]:
print(0.5*(1-np.exp(-2*np.diff(map[l]))))

In [ ]:
# np.set_printoptions(suppress=True)

In [ ]:
def rates2map(rates):
    return (np.cumsum(-0.5*np.log(1-(2*RecombinationRates))))

In [ ]:
def map2rates(map):
    return(0.5*(1-np.exp(-2*np.diff(map))))

In [ ]:
map2rates(rates2map(RecombinationRates))

In [ ]:
len(rates2map(RecombinationRates))

In [ ]:
map[5]

In [ ]:
map[l]

In [ ]:
np.set_printoptions(suppress=True,
   formatter={'float_kind':'{:f}'.format})

In [ ]:
RecombinationRates[855]

In [ ]:
l = [4,7]

In [ ]:
len(np.insert(RecombinationRates, 0, 99, axis=0))

In [ ]:
v1 = [3,4]
v2 = 0

In [ ]:
cP1V1 = v1
cP1V2 = v2
if isinstance(cP1V1, list):
    cP1V1 = np.asarray(cP1V1)
else:
    cP1V1 = np.asarray([cP1V1])
if isinstance(cP1V2, list):
    cP1V2 = np.asarray(cP1V2)
else:
    cP1V2 = np.asarray([cP1V2])

In [ ]:
%%timeit
list(set([2,3,2,4,6,4,2]) | set([0]))

In [ ]:
[7,8,55]+[4,45]

In [ ]:
a = [5,4,3,2,1]
b = [2,3]

In [ ]:
match = lambda a, b: [ b.index(x)+1 if x in b else None for x in a ]

In [ ]:
match(b,a)

In [ ]:
RecombinationRates[0]

In [ ]:
np.set_printoptions(suppress=True,
   formatter={'float_kind':'{:f}'.format})

In [ ]:
l = list(range(10000))

In [ ]:
%%timeit
random.sample(l, 800)

In [ ]:
%%timeit
np.random.choice(l, size=800, replace=False)

In [ ]:
len(random.sample(l, 800)) == len (np.random.choice(l, size=800, replace=False))

In [ ]:
l1 = [1,2,3,4,5,6,7]
l2 = [22,9,44,1,22,4,22,1]


In [ ]:
match = lambda a, b: [ b.index(x) if x in b else 0 for x in a ]

In [ ]:
match (l1,l2)

In [ ]:
l1 = np.array([1,2,3,4])
z = np.array([1,1,1,1])
k1 = set([1,3,4,5,6,7])

In [ ]:
np.in1d(l1,l2)

In [ ]:
k1 = [1,2,3]

In [ ]:
bool(set(k1) & set (k2))

In [ ]:
q = z[np.in1d(l1,list(k2))] * 0

In [ ]:
q

In [ ]:
z = {1:"z",2:"z"}

In [ ]:
len(z.keys())

In [ ]:
z = []
k = []
p = []
l = 10000
for i in range (l):
    z.append(int(random.random() * 10001))
    k.append(random.randint(0,10000))
    p = random.sample(range(100000), l)

In [ ]:
sns.distplot(z)

In [ ]:
sns.distplot(k)

In [ ]:
sns.distplot(p)

In [ ]:
%%timeit
random.sample(range(10000), l)

In [ ]:
%%timeit
z = []
for i in range (l):
    (int(random.random() * 10001))

In [ ]:
%%timeit
np.random.uniform(0,1,10001)

In [ ]:
x = [1]*1000

In [ ]:
%%timeit
x == [1] * len(x)

In [ ]:
sum([0.1,0.1,0.1])

In [ ]:
0.1*2

In [ ]:
z = [1,2,3,4,5,6,7,8,9]

In [ ]:
sum([x for k, x in enumerate(z) if k != 1])

In [ ]:
list(set([4,4,5,3,2,1,1]))[2]

In [ ]:
k = set([4,4,4,4,4,5])

In [ ]:
@njit
def search(inp, setx):
    if inp in setx:
        return (True)

In [ ]:
search(4,k)

In [ ]:
k = list(range(1000000))
z = np.asarray(k)

In [ ]:
%%timeit
sum(k)

In [ ]:
%%timeit
np.sum(k)

In [ ]:
v1 = [0,0,[1],0,0]
v2 = [0,0,0,0,0]
fq = [0.1,0.2,0.3,0.4,0.5]

In [ ]:
np.array([v1,v2,fq,], dtype="object").T

In [ ]:
np.c_[v1,v2]

In [ ]:
if all(np.array_equal(v, [0, 0]) for v in np.c_[v1, v2]) :
       print (True)
else:
    print (False)

In [ ]:
tauList = [0.0, 1.0]
[0.5, 0.5, 0.5, 0.5, 0.2, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.2, 0.5, 0.5, 0.5, 0.5, 0.2, 0.5]
for i in range(len(tauList)):
    print([x for k, x in enumerate(tauList) if k != i])

In [ ]:
eta = 0.0
TEfamily = [2, 1, 2, 2, 2, 2, 2]
TEfamilySet = {1, 2}
tauList = [0.0, 1.0]
for i in range(len(tauList)):
    netTau = tauList[i] - (
        (sum([x for k, x in enumerate(tauList) if k != i]))
        * eta
    )
    indices = (TEfamily == list(TEfamilySet)[i]).nonzero()[0]
    TEexcEffective[indices] = TEexcision[indices] - (TEexcision[indices] * netTau)

In [ ]:
0.0
1.0
True4
[2 1 2 2 2 2 2]
{1, 2}
[0.0, 1.0]
[0.5 0.2 0.5 0.5 0.5 0.5 0.5]
[1. 0. 1. 1. 1. 1. 1.]

In [ ]:
TEset = {1 : []}
{k: [] for k in range(1, len(TEset.keys()) + 1)}

In [ ]:
0/1000

In [ ]:
int(10000 * random.random())

In [ ]:
[int(10000 * random.random()) if i not in [2,5,7]]

In [ ]:
tauList = [1,2,1,1,1,1,1]
i = 2
(sum([x for k, x in enumerate(tauList) if k != i])) * 0.2

In [ ]:
l = set([1])

In [ ]:
1 in tauList

In [ ]:
j = {1:3,2:5,3:7}

In [ ]:
[value for key, value in j.items() if key not in [1]]

In [ ]:
import numpy as np
TERegulationSet = {1:1}
eta = 0
TEexcision = np.asarray([1,1,1,1,1,1,1,1])
TEfamily = np.asarray([1,1,1,1,1,1,1,1])
TEexcEffective = np.zeros(len(TEexcision))

In [ ]:
for keys in TERegulationSet:
    print([value for key, value in TERegulationSet.items() if key != keys])

In [ ]:
import numpy as np
TERegulationSet = {1:1}
eta = 0
TEexcision = np.asarray([1,1,1,1,1,1,1,1])
TEfamily = np.asarray([1,1,1,1,1,1,1,1])
TEexcEffective = np.zeros(len(TEexcision))

for keys in TERegulationSet.keys():
    TERegulationSet[keys] = TERegulationSet[keys] + (
        sum(
            [
                value
                for key, value in TERegulationSet.items()
                if key != keys
            ]
        )
        * eta
    )
    if TERegulationSet[keys] > 1:
        TERegulationSet[keys] = 1.0
    indices = (TEfamily == keys).nonzero()[0]
    print (indices)
    TEexcEffective[indices] = TEexcision[indices] - (TEexcision[indices] * TERegulationSet[keys])
print (TEexcEffective)

In [ ]:
parameters = {
    "generations": 10000,
    "selectionPenaltyMin": 0.0,
    "selectionPenaltyMax": 1.0,
    "etaMin": 0.0,
    "etaMax": 1.0,
    "tauMin": 0.5,
    "tauMax": 1.0,
    "ExcisionRateMainMin": 0.0,
    "ExcisionRateMainMax": 1.0,
    "ExcisionRateHGTMin": 0.0,
    "ExcisionRateHGTMax": 1.0,
    "FrequencyOfInsertionMainMin": 0.1,
    "FrequencyOfInsertionMainMax": 1.0,
    "FrequencyOfInsertionHGTMax": 0.1,
    "FrequencyOfInsertionHGTMin": 1.0,
    "HGTgenerationMin": 5,
    "HGTgenerationMax": 8000,
    "maxProcceses": 72,
}

In [ ]:
from itertools import repeat,cycle